# for Watermill development purposes.
# For Watermill based application docker please check https://watermill.io/docs/getting-started/

version: '3'
services:
  redis:
    image: redis:7
    ports:
      - 6379:6379
    restart: unless-stopped
  redis4.0:
    image: redis:4.0.10
    ports:
      - 6379:6379
    restart: unless-stopped